[2025-07-29 03:40:47,057] ERROR: ERROR: Traceback (most recent call last):
  File "G:\My Drive\Code\Python\cubist_art\cubist_gui_main.py", line 70, in run_process
    result_path = run_cubist(input_path, output_dir, mask_path, total_points, clip_to_alpha)
  File "G:\My Drive\Code\Python\cubist_art\cubist_core_logic.py", line 9, in run_cubist
    import cv2
ModuleNotFoundError: No module named 'cv2'

[2025-07-29 03:42:34,933] ERROR: ERROR: Traceback (most recent call last):
  File "G:\My Drive\Code\Python\cubist_art\cubist_gui_main.py", line 70, in run_process
    result_path = run_cubist(input_path, output_dir, mask_path, total_points, clip_to_alpha)
  File "G:\My Drive\Code\Python\cubist_art\cubist_core_logic.py", line 9, in run_cubist
    import cv2
ModuleNotFoundError: No module named 'cv2'

[2025-07-29 03:45:19,323] ERROR: ERROR: Traceback (most recent call last):
  File "G:\My Drive\Code\Python\cubist_art\cubist_gui_main.py", line 70, in run_process
    result_path = run_cubist(input_path, output_dir, mask_path, total_points, clip_to_alpha)
  File "G:\My Drive\Code\Python\cubist_art\cubist_core_logic.py", line 9, in run_cubist
    import cv2
ModuleNotFoundError: No module named 'cv2'

[2025-07-29 03:45:25,702] ERROR: ERROR: Traceback (most recent call last):
  File "G:\My Drive\Code\Python\cubist_art\cubist_gui_main.py", line 70, in run_process
    result_path = run_cubist(input_path, output_dir, mask_path, total_points, clip_to_alpha)
  File "G:\My Drive\Code\Python\cubist_art\cubist_core_logic.py", line 9, in run_cubist
    import cv2
ModuleNotFoundError: No module named 'cv2'

[2025-07-30 13:26:27,896] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-07-30 13:47:38,993] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-07-30 14:08:34,746] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-07-30 14:09:24,094] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-07-30 14:20:57,652] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-07-30 14:21:47,239] ERROR: EXCEPTION: invalid_mode failed with error: [ValueError: Unsupported geometry mode: invalid_mode]
[2025-08-02 12:43:57,127] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:43:57,149] ERROR: Test 2 FAILED: delaunay (cascade)
[2025-08-02 12:44:06,260] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:44:06,274] ERROR: Test 4 FAILED: voronoi (cascade)
[2025-08-02 12:53:12,610] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:53:12,635] ERROR: Test 2 FAILED: delaunay (cascade)
[2025-08-02 12:53:19,414] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:53:19,428] ERROR: Test 4 FAILED: voronoi (cascade)
[2025-08-02 12:56:30,559] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:56:30,581] ERROR: Test 2 FAILED: delaunay (cascade)
[2025-08-02 12:56:38,127] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 12:56:38,141] ERROR: Test 4 FAILED: voronoi (cascade)
[2025-08-02 13:14:38,724] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 13:14:38,743] ERROR: Test 2 FAILED: delaunay (cascade)
[2025-08-02 13:14:54,923] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 13:14:54,935] ERROR: Test 4 FAILED: voronoi (cascade)
[2025-08-02 13:18:43,322] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 13:18:43,343] ERROR: Test 2 FAILED: delaunay (cascade)
[2025-08-02 13:19:00,281] ERROR: Test failed: OpenCV(4.12.0) :-1: error: (-5:Bad argument) in function 'fillConvexPoly'
> Overload resolution failed:
>  - img data type = bool is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

[2025-08-02 13:19:00,296] ERROR: Test 4 FAILED: voronoi (cascade)
